apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: pod-reader
      automountServiceAccountToken: true
      containers:
        - name: my-app
          image: quay.io/sbaumer/debug-monitor@sha256:f810ef2b209678cd23fd5aa924c65edb679efa9390a8826f44c5cc040ce44a31
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-admin
subjects:
  - kind: ServiceAccount
    name: pod-reader
    namespace: stackrox
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pod-reader
  namespace: stackrox

---
